apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1-deployment
  # namespace: yayobe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp1
  template: 
    metadata: # Dictionary
      name: myapp1-pod
      labels: # Dictionary 
        app: myapp1       
    spec:
      containers: # List
        - name: myapp1-container
          image: yadugna5/yayobegsite2022
          ports:
            - containerPort: 80